Controllers/GuidesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using college_assignment_mvc_project.Models;
using Microsoft.AspNetCore.Http;
using college_assignment_mvc_project.Models.ViewModels;

namespace college_assignment_mvc_project.Controllers
{
    public class GuidesController : Controller
    {
        private readonly college_assignment_mvc_projectContext _context;

        private IActionResult redirect_to_login_page()
        {
            TempData["must-login-msg"] = "<p>Must log in to see this page</p>";
            return RedirectToAction("Login", "Home");
        }
        public GuidesController(college_assignment_mvc_projectContext context)
        {
            _context = context;
        }

        // GET: Guides
        public async Task<IActionResult> Index()
        {
            if (!AuthorizationMiddleware.IsUserLoggedIn(HttpContext.Session))
                return redirect_to_login_page();
            return View(await _context.Guide.ToListAsync());
        }

        // GET: Guides/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (!AuthorizationMiddleware.IsUserLoggedIn(HttpContext.Session))
                return redirect_to_login_page();
            else if (!(AuthorizationMiddleware.IsGuideAuthorized(HttpContext.Session) 
                        || AuthorizationMiddleware.IsAdminAuthorized(HttpContext.Session)))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                return NotFound();
            }

            var guide = await _context.Guide
                .FirstOrDefaultAsync(m => m.GuideID == id);
            if (guide == null)
            {
                return NotFound();
            }

            return View(guide);
        }

        // GET: Guides/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Guides/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GuideID,UserID,FirstName,LastName,PricePerDay,Rate")] Guide guide)
        {
            if (ModelState.IsValid)
            {
                _context.Guide.Add(guide);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(guide);
        }

        // GET: Guides/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guide = await _context.Guide.FindAsync(id);
            if (guide == null)
            {
                return NotFound();
            }
            return View(guide);
        }

        // POST: Guides/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GuideID,UserID,FirstName,LastName,PricePerDay,Rate")] Guide guide)
        {
            if (id != guide.GuideID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(guide);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GuideExists(guide.GuideID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(guide);
        }

        // GET: Guides/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guide = await _context.Guide
                .FirstOrDefaultAsync(m => m.GuideID == id);
            if (guide == null)
            {
                return NotFound();
            }

            return View(guide);
        }

        // POST: Guides/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var guide = await _context.Guide.FindAsync(id);
            _context.Guide.Remove(guide);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GuideExists(int id)
        {
            return _context.Guide.Any(e => e.GuideID == id);
        }

        public IActionResult GetGuidesStats()
        {
            var orders = (from order in _context.Order
                          join guide in _context.Guide on order.SelectedGuildeID equals guide.GuideID
                          select new OrderedGuide
                          {
                              TimesOrderd = 1,
                              GuideName = guide.FirstName + " " + guide.LastName,
                              GuideID = guide.GuideID
                          }).ToList();

            var ordered_guides = new Dictionary<int, OrderedGuide>();
            var guides_ids = (from guide in _context.Guide select guide.GuideID).ToList();

            foreach (var guide_id in guides_ids)
                ordered_guides[guide_id] = new OrderedGuide { GuideID = guide_id, TimesOrderd = 0, GuideName = "" };

            foreach (var order in orders)
            {
                ordered_guides[order.GuideID].TimesOrderd += 1;
                ordered_guides[order.GuideID].GuideName = order.GuideName;
            }

            List<OrderedGuide> orderd_guides = new List<OrderedGuide>(ordered_guides.Count);
            foreach (var ordered_guide in ordered_guides.Values)
            {
                if (ordered_guide.TimesOrderd > 0)
                    orderd_guides.Add(ordered_guide);
            }

            return Json(orderd_guides);
        }

        public IActionResult Stats()
        {
            return View();
        }
    }
}

Controllers/UsersController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using college_assignment_mvc_project.Models;
using Microsoft.AspNetCore.Http;

namespace college_assignment_mvc_project.Controllers
{
    public class UsersController : Controller
    {
        private readonly college_assignment_mvc_projectContext _context;

        public UsersController(college_assignment_mvc_projectContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            if (AuthorizationMiddleware.IsAdminAuthorized(HttpContext.Session) 
                && AuthorizationMiddleware.IsUserLoggedIn(HttpContext.Session))
                return View(await _context.User.ToListAsync());
            return RedirectToAction("UnauthorizedAction", "Home");
        }

        // GET: Users/Details
        public async Task<IActionResult> Details(int? id)
        {
            if (HttpContext.Session.GetString("Role") != "ADMIN")
            {
                return RedirectToAction("UnauthorizedAction", "Home");
            }
            else
            {
                if (id == null)
                    return NotFound();

                var user = await _context.User.FirstOrDefaultAsync(m => m.UserID == id);
                if (user == null)
                    return NotFound();
                
                return View(user);
            }
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            if (!AuthorizationMiddleware.IsUserLoggedIn(HttpContext.Session))
                return View();
            return RedirectToAction("UnauthorizedAction", "Home");
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserID,Email,Password,FirstName,LastName,PhoneNumber")] User user)
        {
            if (!AuthorizationMiddleware.IsUserLoggedIn(HttpContext.Session))
            {
                if (ModelState.IsValid)
                {
                    user.Role = UserAuthorization.USER;
                    _context.Add(user);
                    _context.SaveChanges();

                    // When you create a user we beleive he will automaticly sign in
                    var usr = _context.User.Single(u => u.Email.Equals(user.Email) && u.Password.Equals(user.Password));
                    HttpContext.Session.SetString("UserFirstName", usr.FirstName);
                    HttpContext.Session.SetString("Role", usr.Role.ToString());
                    HttpContext.Session.SetString("IsUserLoggedIn", "UserConnected");
                    HttpContext.Session.SetString("UserID", usr.UserID.ToString());
                }
                else
                    return View(user);
            }

            return RedirectToAction("Index", "Home");
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);            
            if (user == null)
            {
                return NotFound();
            }
            
            if (HttpContext.Session.GetString("IsUserLoggedIn") == "UserConnected" 
                && (HttpContext.Session.GetString("UserFirstName") == user.FirstName 
                    || HttpContext.Session.GetString("Role") == "ADMIN"))
            {
                return View(user);
            }
            return RedirectToAction("UnauthorizedAction", "Home");
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserID,Email,Password,FirstName,LastName,PhoneNumber,Role")] User user)
        {
            if (id != user.UserID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.UserID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                // Handle situation of create new guide
                try
                {
                    var update_user_from_db = _context.User.Where(usr => usr.UserID == user.UserID).First();
                    var guide_from_db = _context.Guide.Where(guide => guide.UserID == user.UserID).First();
                    if (guide_from_db != null)
                    {
                        if (update_user_from_db.Role != UserAuthorization.GUIDE)
                        {
                            // Means we have to try to remove the guide from guides
                            try
                            {
                                _context.Guide.Remove(guide_from_db);
                                _context.SaveChanges();
                            }
                            catch
                            {        
                            }
                        }
                    }
                    
                }
                catch
                {
                    // If we set user to be guide in the first time
                    if (user.Role == UserAuthorization.GUIDE)
                    {
                        var newGuide = new Guide
                        {
                            UserID = user.UserID,
                            FirstName = user.FirstName,
                            LastName = user.LastName
                        };
                        _context.Guide.Add(newGuide);
                    }
                }
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.UserID == id);
            if (user == null)
            {
                return NotFound();
            }
            
            if (!(AuthorizationMiddleware.IsAdminAuthorized(HttpContext.Session) 
                && AuthorizationMiddleware.IsUserLoggedIn(HttpContext.Session)))
            {
                return RedirectToAction("UnauthorizedAction", "Home");
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.User.FindAsync(id);
            var guide = await _context.Guide.FirstOrDefaultAsync(g => g.UserID == id);

            _context.User.Remove(user);
            _context.Guide.Remove(guide);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.User.Any(e => e.UserID == id);
        }
    }
}

Views/Shared/UnauthorizedAction.cshtml
@{
    ViewData["Title"] = "Unauthorized";
    Layout = "";
}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Trip Finder</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <br><br><br>

    <div class="signup-form">
        <h2>You are not allowed to continue</h2>
        <a href="/">Back to home page</a>
    </div>

</body>
</html>

Views/Shared/_Layout.cshtml
@{
    @using Microsoft.AspNetCore.Http;
    var userFirstName = Context.Session.GetString("UserFirstName");
    var role = Context.Session.GetString("Role");
    var userConnected = Context.Session.GetString("IsUserLoggedIn");
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Trip Finder</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Trip Finder</a>
                <span class="navbar-brand">Hello @userFirstName</span>
            </div>

            <div class="navbar-collapse collapse">
                <div class="navbar-header weather-header">
                    <div id="openweathermap-widget-19"></div>
                    <script>
                        window.myWidgetParam ? window.myWidgetParam : window.myWidgetParam = []; window.myWidgetParam.push({ id: 19, cityid: '294801', appid: '8cf322aa089137bed2277b06542c2171', units: 'metric', containerid: 'openweathermap-widget-19', }); (function () { var script = document.createElement('script'); script.async = true; script.charset = "utf-8"; script.src = "//openweathermap.org/themes/openweathermap/assets/vendor/owm/js/weather-widget-generator.js"; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(script, s); })();
                    </script>
                </div>

                <div class="nav navbar-nav navbar-right">
                    <form class="navbar-form navbar-left" action="/Home/Search?search=search">
                        <div class="input-group search">
                            <input type="text" class="form-control" name="search" placeholder="Search Trip or Location">
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit">
                                    <i class="glyphicon glyphicon-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    @if (userConnected == "UserNotConnected")
                    {
                        <span>
                            <a asp-area="" asp-controller="Home" asp-action="Login" class="navbar-brand">
                                <span class="glyphicon glyphicon-log-in"></span>
                                Login
                            </a>
                        </span>
                        <span>
                            <a asp-area="" asp-controller="Users" asp-action="Create" class="navbar-brand">
                                <span class="glyphicon glyphicon-user"></span>
                                Sign In
                            </a>
                        </span>
                    }

                    else if (userConnected == "UserConnected")
                    {

                        <span>
                            <a asp-area="" asp-controller="Home" asp-action="Cart" class="navbar-brand">
                                <span class="glyphicon glyphicon-shopping-cart"></span>
                            </a>
                        </span>

                        <span>
                            <a asp-area="" asp-controller="Home" asp-action="Logout" class="navbar-brand">
                                <span class="glyphicon glyphicon-user"></span>
                                Logout
                            </a>
                        </span>
                    }

                    @if (role == "ADMIN")
                    {
                        <span>
                            <a asp-area="" asp-controller="Users" asp-action="Index" class="navbar-brand">
                                <span class="glyphicon glyphicon-user"></span>
                                Users Administration
                            </a>
                        </span>
                    }

                    @if (role == "ADMIN" || role == "GUIDE")
                    {
                        <span>
                            <a asp-area="" asp-controller="Tracks" asp-action="Create" class="navbar-brand">
                                <span class="glyphicon glyphicon-user"></span>
                                Add New Track
                            </a>
                        </span>
                    }


                </div>
                @if (userConnected == "UserConnected")
                {
                    <span>
                        <a asp-area="" asp-controller="Guides" asp-action="Stats" class="navbar-brand">
                            <span class="glyphicon glyphicon-user"></span>
                            Top Guid
                        </a>
                    </span>
                    <span>
                        <a asp-area="" asp-controller="Orders" asp-action="Stats" class="navbar-brand">
                            <span class="glyphicon glyphicon-user"></span>
                            Top Order
                        </a>
                    </span>
                }


                </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Trip Finder</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>