Controllers/GuidesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using college_assignment_mvc_project.Models;
using Microsoft.AspNetCore.Http;
using college_assignment_mvc_project.Models.ViewModels;

namespace college_assignment_mvc_project.Controllers
{
    public class GuidesController : Controller
    {
        private readonly college_assignment_mvc_projectContext _context;

        private IActionResult redirect_to_login_page()
        {
            TempData["must-login-msg"] = "<p>Must log in to see this page</p>";
            return RedirectToAction("Login", "Home");
        }
        public GuidesController(college_assignment_mvc_projectContext context)
        {
            _context = context;
        }

        // GET: Guides
        public async Task<IActionResult> Index()
        {
            if (!AuthorizationMiddleware.IsUserLoggedIn(HttpContext.Session))
                return redirect_to_login_page();
            return View(await _context.Guide.ToListAsync());
        }

        // GET: Guides/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (!AuthorizationMiddleware.IsUserLoggedIn(HttpContext.Session))
                return redirect_to_login_page();
            else if (!(AuthorizationMiddleware.IsGuideAuthorized(HttpContext.Session) 
                        || AuthorizationMiddleware.IsAdminAuthorized(HttpContext.Session)))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                return NotFound();
            }

            var guide = await _context.Guide
                .FirstOrDefaultAsync(m => m.GuideID == id);
            if (guide == null)
            {
                return NotFound();
            }

            return View(guide);
        }

        // GET: Guides/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Guides/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GuideID,UserID,FirstName,LastName,PricePerDay,Rate")] Guide guide)
        {
            if (ModelState.IsValid)
            {
                _context.Guide.Add(guide);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(guide);
        }

        // GET: Guides/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guide = await _context.Guide.FindAsync(id);
            if (guide == null)
            {
                return NotFound();
            }
            return View(guide);
        }

        // POST: Guides/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GuideID,UserID,FirstName,LastName,PricePerDay,Rate")] Guide guide)
        {
            if (id != guide.GuideID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(guide);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GuideExists(guide.GuideID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(guide);
        }

        // GET: Guides/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guide = await _context.Guide
                .FirstOrDefaultAsync(m => m.GuideID == id);
            if (guide == null)
            {
                return NotFound();
            }

            return View(guide);
        }

        // POST: Guides/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var guide = await _context.Guide.FindAsync(id);
            _context.Guide.Remove(guide);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GuideExists(int id)
        {
            return _context.Guide.Any(e => e.GuideID == id);
        }

        public IActionResult GetGuidesStats()
        {
            var orders = (from order in _context.Order
                          join guide in _context.Guide on order.SelectedGuildeID equals guide.GuideID
                          select new OrderedGuide
                          {
                              TimesOrderd = 1,
                              GuideName = guide.FirstName + " " + guide.LastName,
                              GuideID = guide.GuideID
                          }).ToList();

            var ordered_guides = new Dictionary<int, OrderedGuide>();
            var guides_ids = (from guide in _context.Guide select guide.GuideID).ToList();

            foreach (var guide_id in guides_ids)
                ordered_guides[guide_id] = new OrderedGuide { GuideID = guide_id, TimesOrderd = 0, GuideName = "" };

            foreach (var order in orders)
            {
                ordered_guides[order.GuideID].TimesOrderd += 1;
                ordered_guides[order.GuideID].GuideName = order.GuideName;
            }

            List<OrderedGuide> orderd_guides = new List<OrderedGuide>(ordered_guides.Count);
            foreach (var ordered_guide in ordered_guides.Values)
            {
                if (ordered_guide.TimesOrderd > 0)
                    orderd_guides.Add(ordered_guide);
            }

            return Json(orderd_guides);
        }

        public IActionResult Stats()
        {
            return View();
        }
    }
}

Controllers/TracksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using college_assignment_mvc_project.Models;

namespace college_assignment_mvc_project.Controllers
{
    public class TracksController : Controller
    {
        private readonly college_assignment_mvc_projectContext _context;

        public TracksController(college_assignment_mvc_projectContext context)
        {
            _context = context;
        }

        // GET: Tracks
        public async Task<IActionResult> Index()
        {
            var college_assignment_mvc_projectContext = _context.Track.Include(t => t.Guide);
            return View(await college_assignment_mvc_projectContext.ToListAsync());
        }

        // GET: Tracks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var track = await _context.Track
                .Include(t => t.Guide)
                .FirstOrDefaultAsync(m => m.TrackID == id);
            if (track == null)
            {
                return NotFound();
            }

            ViewData["TrackID"] = track.TrackID;

            ViewData["GuideName"] = track.Guide.FirstName + " " + track.Guide.LastName;
            ViewData["GuideRate"] = track.Guide.Rate;

            TempData["TrackID"] = track.TrackID;
            TempData["GuideID"] = track.GuideId;

            return View(track);
        }

        // GET: Tracks/Create
        public IActionResult Create()
        {
            if (!AuthorizationMiddleware.IsUserLoggedIn(HttpContext.Session))
            {
                return RedirectToAction("UnauthorizedAction", "Home");
            }
            else if (!AuthorizationMiddleware.IsItGuideOrAdmin(HttpContext.Session))
            {
                return RedirectToAction("UnauthorizedAction", "Home");
            }
            var college_assignment_mvc_projectContext = _context.Track.Include(t => t.Guide);
            ViewData["Guide"] = new SelectList(_context.Set<Guide>().Select(g => new
            {
                g.GuideID,
                FullName = g.FirstName + " " + g.LastName
            }).ToList(), "GuideID", "FullName");

            return View();

        }

        // POST: Tracks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TrackID,Name,Location,Difficulty,Image,Lat,Long,Rate,Includes_Water,Circular,Duration,TrackLenght,GuideId")] Track track)
        {
            if (ModelState.IsValid)
            {
                _context.Add(track);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Guide"] = new SelectList(_context.Set<Guide>(), "GuideID", "GuideID", track.GuideId);
            return View(track);
        }

        // GET: Tracks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!AuthorizationMiddleware.IsUserLoggedIn(HttpContext.Session))
            {
                return RedirectToAction("UnauthorizedAction", "Home");
            }
            else if (!AuthorizationMiddleware.IsItGuideOrAdmin(HttpContext.Session))
            {
                return RedirectToAction("UnauthorizedAction", "Home");
            }

            if (id == null)
            {
                return NotFound();
            }

            var track = await _context.Track.FindAsync(id);
            if (track == null)
            {
                return NotFound();
            }
            ViewData["GuideId"] = new SelectList(_context.Set<Guide>().Select(g => new
            {
                g.GuideID,
                FullName = g.FirstName + " " + g.LastName
            }).ToList(), "GuideID", "FullName");

            return View(track);
        }

        public async Task<IActionResult> Info(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var track = await _context.Track.FindAsync(id);
            if (track == null)
            {
                return NotFound();
            }
            ViewData["GuideId"] = new SelectList(_context.Set<Guide>(), "GuideID", "GuideID", track.GuideId);
            return View(track);
        }

        // POST: Tracks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TrackID,Name,Location,Difficulty,Image,Lat,Long,Rate,Includes_Water,Circular,Duration,TrackLenght,GuideId")] Track track)
        {
            if (id != track.TrackID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(track);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TrackExists(track.TrackID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GuideId"] = new SelectList(_context.Set<Guide>(), "GuideID", "GuideID", track.GuideId);
            return View(track);
        }

        // GET: Tracks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var track = await _context.Track
                .Include(t => t.Guide)
                .FirstOrDefaultAsync(m => m.TrackID == id);
            if (track == null)
            {
                return NotFound();
            }

            return View(track);
        }

        // POST: Tracks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var track = await _context.Track.FindAsync(id);
            _context.Track.Remove(track);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TrackExists(int id)
        {
            return _context.Track.Any(e => e.TrackID == id);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Cart.cshtml
@model IEnumerable<college_assignment_mvc_project.Models.Order>

@{
    ViewData["Title"] = "Cart";
    Dictionary<int, string> trackName = (Dictionary<int, string>)ViewData["dictionary"];
}

<div class="row">
    <div class="col-lg-12 text-center">
        <br><br><br>
        <hr>
        <h1>My Orders</h1>
        <hr>
        <br>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PurchasedTrackID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SelectedGuildeID)
            </th>
            <th>
               Name Track
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                <a asp-controller="Tracks" asp-action="Info" asp-route-id="@item.PurchasedTrackID">
                    @Html.DisplayFor(modelItem => item.PurchasedTrackID)
                </a>
            </td>
            <td>
                <a asp-controller="Guides" asp-action="Details" asp-route-id="@item.SelectedGuildeID">
                    @Html.DisplayFor(modelItem => item.SelectedGuildeID)
                </a>
            </td>
            <td>
                @trackName[item.PurchasedTrackID]
            </td>
        </tr>
        }
    </tbody>
</table>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@model IEnumerable<college_assignment_mvc_project.Models.Track>

@{
    @using Microsoft.AspNetCore.Http;
    ViewData["Title"] = "Home Page";
    var recomendedTrack = (Track)ViewData["RecomendedTrack"];
    var userConnected = Context.Session.GetString("IsUserLoggedIn");
    var userFirstName = Context.Session.GetString("UserFirstName");
}

@Html.Raw(TempData["invalid-action"])

<div class="row ">
    <div class="col-lg-12 text-center">
        <br><br><br>
        <hr>
        <h1 class="tagline">The Best Trips, Just For You</h1>
        <p>Find tracks & guides just for you! and start enjoying Earth </p>
        <iframe width="600" height="200" src="https://www.youtube.com/embed/n9orHWu8zQA?autoplay=1"></iframe>
        <hr>
        <br>
    </div>
</div>

<div class="bs-example">
    <div id="myCarousel" class="carousel" data-ride="carousel">
        <div class="carousel-inner">
            @{int i = 0;}
            @foreach (var item in Model)
            {
                if (i == 0)
                {
                    <div class="item active">
                        <img class="track-image" src="@item.Image" alt="IMAGES" />
                        <a asp-controller="Tracks" asp-action="Details" asp-route-id="@item.TrackID"><h4> @item.Name </h4></a>
                        <span>@item.Location</span>
                    </div>
                }
                else
                {
                    <div class="item">
                        <img class="track-image" src="@item.Image" alt="IMAGES" />
                        <a asp-controller="Tracks" asp-action="Details" asp-route-id="@item.TrackID"><h4> @item.Name </h4></a>
                        <span>@item.Location</span>
                    </div>
                }
                i++;
            }







        </div>
        <a class="carousel-control left" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="carousel-control right" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>

    </div>
</div>
@if (userConnected == "UserConnected" && recomendedTrack != null)
{
    <div class="bs-example">
        <div id="myCarousel" class="carousel" data-ride="carousel">
            <div class="carousel-inner">
                <div class="item active">

                        <h3 class="carousel">Recomended Track For You, @userFirstName</h3>
                        <tr>
                            <td>
                                <a asp-controller="Tracks" asp-action="Details" asp-route-id="@recomendedTrack.TrackID">
                                    <h4>@recomendedTrack.Name</h4>
                                </a>
                            </td>
                            <td>
                                <img class="track-image" src="@recomendedTrack.Image" alt="IMAGES" />
                            </td>
                        </tr>
                        
                 </div>
             </div>
         </div>
     </div>

}

Views/Home/Login.cshtml
@{
    ViewData["Title"] = "Login";
    var invalid_login_message = TempData["login-failure"] == null ? null : "<p class=login-failure>Your email or password is incorrect.Please check your email or password and try again.</p>";
}

<br><br><br>

<div class="signup-form">
    <form asp-action="Login" method="post">
        <h2>Login</h2>
        <p class="hint-text">Login to your existing account</p>
        @Html.Raw(@invalid_login_message)

        <div class="form-group">
            <input type="email" class="form-control" name="email" placeholder="Email" required="required">
        </div>

        <div class="form-group">
            <input type="password" class="form-control" name="password" placeholder="Password" required="required">
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-success btn-lg btn-block">Log In</button>
        </div>
    </form>
</div>


Views/Home/Search.cshtml
@{
    ViewData["Title"] = "Search";
}

<div class="row ">
    <div class="col-lg-12 text-center">
        <br><br><br>
        <hr>
        <h1 class="tagline">@ViewData["Title"]</h1>
        <p>Searching for the following: @ViewData["Message"]</p>
        <hr>
        <br>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <td>
                Name
            </td>
            <td>
                Location
            </td>
            <td>
                Rate
            </td>
            <td>
                Image
            </td>
        </tr>

        @foreach (var track in (List<Track>)@ViewData["Result"])
        {
            <tr>
                <td>
                    <a asp-controller="Tracks" asp-action="Details" asp-route-id="@track.TrackID">
                        <h4>@track.Name</h4>
                    </a>
                </td>
                <td>
                    @track.Location
                </td>
                <td>
                    @track.Rate
                </td>
                <td>
                    <img class="track-image" src="@track.Image" alt="IMAGES" />
                </td>
            </tr>
        }
    </thead>
</table>